name: Payload

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - name: Check out source code
      uses: actions/checkout@v3
    - name: Use Node.js version ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: payload/package-lock.json
    - run: |
        cd payload/
        npm ci
    - name: Run the unit tests
      run: |
        cd payload/
        npm test
